FROM nginx:alpine


EXPOSE 8887


# RUN apk update && apk add openssl && openssl req -x509 -nodes \
#     -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key \
#     -out /etc/ssl/certs/nginx-selfsigned.crt -batch


COPY srcs/ /var/www/html

# RUN mkdir /var/www/html/static/bootstrap && mkdir /var/www/html/static/bootstrap/js && mkdir /var/www/html/static/bootstrap/css

# COPY bootstrap/css/* /var/www/html/static/bootstrap/css

# COPY bootstrap/js/* /var/www/html/static/bootstrap/js

RUN echo "" >  /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
